#ifndef __INSTRUCTIONS__
#define __INSTRUCTIONS__

#include <stdint.h>

int asm_adc(uint16_t);
int asm_and(uint16_t);
int asm_asl(uint16_t);
int asm_asla(uint16_t);
int asm_bit(uint16_t);
int asm_bpl(uint16_t);
int asm_bmi(uint16_t);
int asm_bvc(uint16_t);
int asm_bvs(uint16_t);
int asm_bcc(uint16_t);
int asm_bcs(uint16_t);
int asm_bne(uint16_t);
int asm_beq(uint16_t);
int asm_brk(uint16_t);
int asm_cmp(uint16_t);
int asm_cpx(uint16_t);
int asm_cpy(uint16_t);
int asm_dec(uint16_t);
int asm_eor(uint16_t);
int asm_clc(uint16_t);
int asm_sec(uint16_t);
int asm_cli(uint16_t);
int asm_sei(uint16_t);
int asm_clv(uint16_t);
int asm_cld(uint16_t);
int asm_sed(uint16_t);
int asm_inc(uint16_t);
int asm_jmp(uint16_t);
int asm_jsr(uint16_t);
int asm_lda(uint16_t);
int asm_ldx(uint16_t);
int asm_ldy(uint16_t);
int asm_lsr(uint16_t);
int asm_lsra(uint16_t);
int asm_nop(uint16_t);
int asm_ora(uint16_t);
int asm_tax(uint16_t);
int asm_txa(uint16_t);
int asm_dex(uint16_t);
int asm_inx(uint16_t);
int asm_tay(uint16_t);
int asm_tya(uint16_t);
int asm_dey(uint16_t);
int asm_iny(uint16_t);
int asm_rol(uint16_t);
int asm_rola(uint16_t);
int asm_ror(uint16_t);
int asm_rora(uint16_t);
int asm_rti(uint16_t);
int asm_rts(uint16_t);
int asm_sbc(uint16_t);
int asm_sta(uint16_t);
int asm_txs(uint16_t);
int asm_tsx(uint16_t);
int asm_pha(uint16_t);
int asm_pla(uint16_t);
int asm_php(uint16_t);
int asm_plp(uint16_t);
int asm_stx(uint16_t);
int asm_sty(uint16_t);

#endif
